name: Build documentation and tag a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag"
        required: true

jobs:
  build-doc-and-tag:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang 
        uses: actions/setup-go@v4
     
      - name: Build and tag a release
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          go generate ./...
          git add ./docs
          git commit -am "[auto] docs for ${{ inputs.version }}"
          git push origin main
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
