name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to tag"
        required: true

permissions:
  contents: write

jobs:
  build-doc-and-tag:
    name: Build documentation and tag release
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang 
        uses: actions/setup-go@v4
     
      - name: Build and push doc
        run: | 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          go generate ./...
          git add ./docs
          git commit -am "[auto] docs for ${{ inputs.version }}"
          git push origin main
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Create tag
        if: success() || failure()
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

  goreleaser:
    name: Build release
    needs: build-doc-and-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Golang 
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
